#!/usr/bin/env ruby
require_relative '../lib/script_helper'

# Create a list of all events associated with the group
class GetEvents
  include ScriptHelper

  def initialize
    @group_name = 'HumanTalks-Paris'
    @api_key = api_key('meetup')

    if @api_key.nil?
      puts 'Cannot find your API key.'
      puts 'Usage:'
      puts 'MEETUP_API_KEY=XXXXXX ./scripts/get_events'
      puts 'Or create a ./_meetup_api_key file in the root folder'
      exit 1
    end
  end

  # Get the whole list of events from the meetup API
  def raw_events
    url = [
      'https://api.meetup.com/2/events?',
      "key=#{@api_key}&",
      "group_urlname=#{@group_name}&",
      'status=past'
    ].join('')

    json = JSON.parse(open(url).read)
    json
  end

  # Return a cleaned up list of events
  def events
    raw = raw_events['results']
    events = raw.map do |event|
      host = event["venue"]["name"]
      count_max = event["rsvp_limit"]
      count_actual = event["yes_rsvp_count"]
      rating = event["rating"]["average"]
      url = event["event_url"]
      name = event["name"]
      talk_id = event["id"]
      date = event["time"]
      _description = event["description"]

      {
        _description: _description,
        talk_id: talk_id,
        host: host,
        name: name,
        url: url,
        count_max: count_max,
        count_actual: count_actual,
        date: date,
        rating: rating
      }
    end
    events
  end

  def run
    write_json("data/events", events)
  end
end
GetEvents.new.run
