#!/usr/bin/env ruby
require 'json'
require 'algoliasearch'

records = JSON.parse(File.open('./data/records.json').read)

app_id = 'O3F8QXYK6R'
api_key = File.read('./_algolia_api_key').chomp
index_name = 'humantalks'
index_name_tmp = 'humantalks_tmp'

settings = {
  attributesToIndex: [
    'unordered(title)',
    'unordered(authors.name)',
    'unordered(location)',
    'unordered(description)'
  ],
  customRanking: [
    'desc(timestamp)'
  ],
  attributesForFacetting: [
    'authors.name',
    'location',
    'date'
  ],
  attributesToSnippet: %w(
    description:50
  ),
  snippetEllipsisText: '…',
  highlightPreTag: '<span class="search-hit--highlight">',
  highlightPostTag: '</span>',
  typoTolerance: 'strict',
  exactOnSingleWordQuery: 'word',
  advancedSyntax: true
}

synonyms = [{
  objectID: 'javascript',
  type: 'synonym',
  synonyms: %w(js javascript)
}, {
  objectID: 'ux',
  type: 'synonym',
  synonyms: ['ux', 'user experience']
}, {
  objectID: 'ui',
  type: 'synonym',
  synonyms: ['ui', 'user interface']
}]


Algolia.init(application_id: app_id, api_key: api_key)
index = Algolia::Index.new(index_name_tmp)
index.set_settings(settings)
index.batch_synonyms(synonyms)
index.add_objects!(records)
Algolia.move_index(index_name_tmp, index_name)
